FProjectCampingBackend/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing.Printing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using FProjectCampingBackend.Models.EFModels;
using FProjectCampingBackend.Models.Repostories;
using FProjectCampingBackend.Models.Services;
using FProjectCampingBackend.Models.ViewModels;
using PagedList;
using PagedList.Mvc;

namespace FProjectCampingBackend.Controllers
{
    public class MembersController : Controller
    {
        private AppDbContext db = new AppDbContext();
        private readonly DropdownListService _dropdownListService =  new DropdownListService();


        // GET: Members
        public ActionResult Index(MemberVm vm, int page = 1, int pageSize = 5)
        {
            ViewData["Enabled"] = _dropdownListService.GetEnabledDropdownList();
            ViewData["IsConfirmed"] = _dropdownListService.GetIsConfirmedDropdownList();
            var repo = new MemberRepository(db);
            IQueryable<Member> query = repo.GetMembers(vm);

           
            var pagedMembers = query.OrderBy(m => m.Id).ToPagedList(page, pageSize);

            return View(pagedMembers);
        }


        public class MemberEnabledSelect
		{
            public Member Id { get; set; }
            public string SelectedEnabled { get; set; }
		}

		// GET: Members/Details/5
		public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // 若要免於大量指派 (overposting) 攻擊，請啟用您要繫結的特定屬性，
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Account,Password,Name,Email,PhoneNum,Birthday,Enabled,Photo,CreatedTime,IsConfirmed,ConfirmCode")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // 若要免於大量指派 (overposting) 攻擊，請啟用您要繫結的特定屬性，
        // 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Account,Password,Name,Email,PhoneNum,Birthday,Enabled,Photo,CreatedTime,IsConfirmed,ConfirmCode")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



	}
}

FProjectCampingBackend/Controllers/OrdersController.cs
using FProjectCampingBackend.Models.EFModels;
using FProjectCampingBackend.Models.Repostories;
using FProjectCampingBackend.Models.Services;
using FProjectCampingBackend.Models.ViewModels.Orders;
using PagedList;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace FProjectCampingBackend.Controllers
{
	public class OrdersController : Controller
	{
		private AppDbContext db = new AppDbContext();
		private readonly OrderService _OrderService = new OrderService();

		// GET: Orders

		public ActionResult Index(SearchParameterVm vm, int page = 1, int pageSize = 15)
		{
			ViewData["Status"] = _OrderService.GetStatusDropdownList();
			var repo = new OrderRepository(db);
			IQueryable<Order> parameter = repo.GetOrders(vm);

			// 遍歷資料庫中的訂單，並將其轉換為 ViewModel
			var result = new List<OrderVm>();
			foreach (var order in parameter)
			{
				var orderVm = new OrderVm()
				{
					Id = order.Id,
					OrderTime = order.OrderTime,
					PaymentType = order.PaymentType.Name,
					Price = order.TotalPrice,
					Status = order.Status.ToString(),
					Member = order.Member.Name,
					Name = order.Name,
					Email = order.Email,
					PhoneNum = order.PhoneNum
				};
				result.Add(orderVm);
			}

			// 使用ToPagedList進行分頁
			var pagedOrders = result.OrderBy(x => x.OrderTime).ToPagedList(page, pageSize);

			return View(pagedOrders);
		}

		// GET: Orders/Details/5
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Order order = db.Orders.Find(id);
			if (order == null)
			{
				return HttpNotFound();
			}
			var result = new List<OrderItemsVm>();
			foreach (var item in order.OrderItems)
			{
				var orderItemsVm = new OrderItemsVm
				{
					RoomType = item.Room.RoomType.Name,
					RoomNum = item.Room.RoomName,
					CheckInDate = item.CheckInDate.ToShortDateString(),
					CheckOutDate = item.CheckOutDate.ToShortDateString(),
					Days = item.Days,
					SubTotal = item.SubTotal
				};
				result.Add(orderItemsVm);
			}
			return View(result);
		}

		// GET: Orders/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Order orders = db.Orders.Find(id);
			if (orders == null)
			{
				return HttpNotFound();
			}
			return View(orders);
		}

		// POST: Orders/Edit/5
		// 若要免於大量指派 (overposting) 攻擊，請啟用您要繫結的特定屬性，
		// 如需詳細資料，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "Id,MemberId,OrderTime,Status,PaymentTypeId,TotalPrice")] Order order)
		{
			if (ModelState.IsValid)
			{
				db.Entry(order).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			ViewBag.MemberId = new SelectList(db.Members, "Id", "Account", order.MemberId);
			ViewBag.PaymentTypeId = new SelectList(db.PaymentTypes, "Id", "Name", order.PaymentTypeId);
			return View(order);
		}

		// GET: Orders/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Order order = db.Orders.Find(id);
			if (order == null)
			{
				return HttpNotFound();
			}
			return View(order);
		}

		// POST: Orders/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Order order = db.Orders.Find(id);
			db.Orders.Remove(order);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

FProjectCampingBackend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Camping放鬆村-後台</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cherry+Bomb+One&family=Dela+Gothic+One&family=Kaisei+Decol&family=Kaisei+Tokumin&family=Mochiy+Pop+P+One&family=Yuji+Mai&display=swap" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("css", required: false)
    <style>
        .hometitle {
            font-family: 'Kaisei Tokumin', serif;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark flex-wrap justify-content-center">
        <div class="container">

            <a class="navbar-brand hometitle" href="@Url.Action("Index", "Home", new { area = "" })">
                <span>
                    <img src="~/images/camping.png" alt="" style="width: 28px;"
                         class="img-fluid align-baseline">
                </span>Camping放鬆村-後台
            </a>
        </div>

        <div class="container">

            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="切換導覽" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("首頁", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("會員管理", "Index", "Members", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("訂單管理", "Index", "Orders", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("房型管理", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - Camping放鬆村</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FProjectCampingBackend/Views/Shared/_mod_lastestMember.cshtml
@model IEnumerable<FProjectCampingBackend.Models.EFModels.Member>
<table class="table table-striped">
    <thead>
        <tr>
            <th>編號</th>
            <th>帳號</th>
            <th>時間</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var member in Model)
        {
            <tr>
                <td>@member.Id</td>
                <td>
                    @if (member.Photo == null)
                    {
                        <img src="/images/camping_no.jpg" alt="大頭照" class="img-fluid memberPhoto">
                    }
                    else
                    {
                        <img src="/files/@Html.DisplayFor(modelItem => member.Photo)" alt="@member.Account" class="img-fluid memberPhoto" />

                    }

                    @member.Account
                </td>

                <td>@member.CreatedTime</td>
            </tr>
        }
    </tbody>
</table>

FProjectCampingBackend/Views/Shared/_mod_newOrder.cshtml
@model IEnumerable<FProjectCampingBackend.Models.EFModels.Order>
<table class="table table-striped">
    <thead>
        <tr>
            <th>編號</th>
            <th>帳號</th>
            <th>時間</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var member in Model)
        {
            <tr>
                <td>@member.Id</td>
                <td>
                    @if (member.Photo == null)
                    {
                        <img src="/images/camping_no.jpg" alt="大頭照" class="img-fluid memberPhoto">
                    }
                    else
                    {
                        <img src="/files/@Html.DisplayFor(modelItem => member.Photo)" alt="@member.Account" class="img-fluid memberPhoto" />

                    }

                    @member.Account
                </td>

                <td>@member.CreatedTime</td>
            </tr>
        }
    </tbody>
</table>