FProjectCamping/Models/EFModels/Cart.cs
namespace FProjectCamping.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cart()
        {
            CartItems = new HashSet<CartItem>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string MemberAccount { get; set; }

        public int TotalPrice { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
    }
}

FProjectCamping/Models/ViewModels/Carts/CartItemRequestModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FProjectCamping.Models.ViewModels.Carts
{
    public class CartItemRequestModel
	{
		public int roomId { get; set; } 
		public int cartId { get; set; }
		public DateTime checkInDate { get; set; } 
		public DateTime checkOutDate { get; set; } 
		public bool extraBed { get; set; } 
		public int extraBedPrice { get; set; } 
		public int days { get; set; }

		public int subtotal { get; set; }

		

	}

}

FProjectCamping/Models/ViewModels/Carts/CartItemsVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace FProjectCamping.Models.ViewModels.Carts
{
	public class CartItemsVm
	{
		/// <summary>
		/// 購物車明細ID
		/// </summary>
		public int Id { get; set; }

		/// <summary>
		/// 房號Key
		/// </summary>
		public int RoomId { get; set; }

		/// <summary>
		/// 房型Key
		/// </summary>
		public string RoomTypeId { get; set; }

		/// <summary>
		/// 房型
		/// </summary>
		[Display(Name = "房型")]
		public string RoomName { get; set; }

		/// <summary>
		/// 房號
		/// </summary>
		[Display(Name = "房號")]
		public string RoomNum { get; set; }

		/// <summary>
		/// 入住日
		/// </summary>
		[Display(Name = "入住日")]
		[DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
		public DateTime CheckInDate { get; set; }

		/// <summary>
		/// 退房日
		/// </summary>
		[Display(Name = "退房日")]
		[DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
		public DateTime CheckOutDate { get; set; }

		/// <summary>
		/// 夜數
		/// </summary>
		[Display(Name = "夜數")]
		public int Days { get; set; }

		/// <summary>
		/// 單價
		/// </summary>
		[Display(Name = "單價")]
		[DisplayFormat(DataFormatString = "{0:#,#}")]
		public int RoomPrice { get; set; }

		/// <summary>
		/// 是否加床
		/// </summary>
		[Display(Name = "是否加床")]
		public bool ExtraBed { get; set; }

		/// <summary>
		/// 加床金額,有加床才有值
		/// </summary>
		[Display(Name = "加床金額")]
		public int ExtraBedPrice { get; set; }

		/// <summary>
		/// 此房號加床的金額
		/// </summary>
		public int ExtraPrice { get; set; }

		/// <summary>
		/// 金額
		/// </summary>
		[Display(Name = "金額")]
		public int SubTotal { get; set; }
	}
}

FProjectCamping/Models/ViewModels/Carts/CartVm.cs
using FProjectCamping.Models.ViewModels.Members;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace FProjectCamping.Models.ViewModels.Carts
{
	public class CartVm
	{
		public int Id { get; set; }

		public string MemberAccount { get; set; }

		public List<CartItemsVm> Items { get; set; }

		//public int TotalPrice => Items.Sum(x => x.SubTotal);

		public int TotalPrice { get; set; }

		public bool AllowCheckout { get; set; } // 至少要有一筆明細資料才可以結帳

		public EditProfileVm ContactProfile { get; set; }

		public string Coupon { get; set; }

		public int PaymentType { get; set; }

		public string Memo { get; set; }
	}
}

FProjectCamping/Models/ViewModels/Carts/CheckoutVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FProjectCamping.Models.ViewModels.Carts
{
    public class CheckoutVm
    {
        [Display(Name = "訂購人姓名")]
        [Required]
        [MaxLength(30)]
        public string Name { get; set; }

        [Display(Name = "手機")]
        [Required]
        [MaxLength(10)]
        public string PhoneNum { get; set; }

        [Display(Name = "電子郵件")]
        [Required]
        public string Email { get; set; }

        [Display(Name = "支付方式")]
        [Required]
        public string PaymnetType { get; set; }

        [Display(Name = "優惠卷")]
        public string Coupon { get; set; }
    }
}

FProjectCamping/Controllers/Cart/CartApiController.cs
using FProjectCamping.Models.EFModels;
using FProjectCamping.Models.Services;
using FProjectCamping.Models.ViewModels.Carts;
using FProjectCamping.Models.ViewModels.Rooms;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace FProjectCamping.Controllers.Cart
{
    public class CartApiController : ApiController
    {
        [HttpPost]
        [Route("api/Cart/GetCartVm")]
        public IHttpActionResult GetCartVm([FromBody] RenameVm vm)
        {
            var db = new AppDbContext();
            var cartItems = new CartItem
            {
                CartId = 9,
                RoomId = 3,
                CheckInDate = vm.StartDateTime,
                CheckOutDate = vm.EndDateTime,
                ExtraBed = true,
                ExtraBedPrice = 100,
                Days = 1,
                SubTotal = 100
            };

            db.CartItems.Add(cartItems);
            db.SaveChanges();

            return Ok();
        }

        //[HttpPost]
        //[Route("api/Cart/AddCartItem")]
        //public IHttpActionResult AddCartItem([FromBody] CartItemRequestModel requestData)
        //{
        //	var db = new AppDbContext();

        //	if (ModelState.IsValid)
        //	{
        //		var cartItem = new CartItem
        //		{
        //			CartId = requestData.cartId,
        //			RoomId = requestData.roomId,
        //			CheckInDate = requestData.checkInDate,
        //			CheckOutDate = requestData.checkOutDate,
        //			ExtraBed = requestData.extraBed,
        //			ExtraBedPrice = requestData.extraBedPrice,
        //			Days = requestData.days,
        //			SubTotal = requestData.subtotal
        //		};

        //		db.CartItems.Add(cartItem);
        //		db.SaveChanges();

        //		return Ok();
        //	}

        //	else
        //	{
        //		return BadRequest(ModelState);
        //	}
        //}

        [HttpPost]
        [Route("api/Cart/AddCartItem")]
        public IHttpActionResult AddCartItem([FromBody] CartItemRequestModel requestData)
        {
            var param = new CartItemsVm() 
            {
                RoomId = requestData.roomId,
                CheckInDate = requestData.checkInDate,
                CheckOutDate = requestData.checkOutDate,
                ExtraBed = requestData.extraBed,
                ExtraBedPrice = requestData.extraBedPrice,
                Days = requestData.days,
                SubTotal = requestData.subtotal
            };

            var service = new CartService();
            string buyer = User.Identity.Name; // 買家帳號
            var result = service.AddToCart(buyer, param); //加入購物車

            return Ok(result);
        }
    }
}

FProjectCamping/Controllers/Cart/CartsController.cs
using FProjectCamping.Models.Services;
using FProjectCamping.Models.ViewModels.Carts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.ApplicationServices;
using System.Web.Mvc;

namespace FProjectCamping.Controllers.Cart
{
	public class CartsController : Controller
	{
		private readonly Models.Services.ProfileService _profileService = new Models.Services.ProfileService();
		private readonly CartService _cartService = new CartService();

		[Authorize]
		public ActionResult Cart()
		{
			// 登入者
			var account = User.Identity.Name;
			var model = _cartService.Get(account);

			return View(model);
		}

		[Authorize]
		[HttpPost]
		public ActionResult Cart(CartVm vm)
		{
			if (vm.Items == null)
			{
				ViewBag.ShowSweetAlert = true;
				return View(vm);
			}

			_cartService.Update(vm);

			return RedirectToAction("OrderInfo");
		}

		[Authorize]
		public ActionResult OrderInfo()
		{
			var account = User.Identity.Name;
			var cart = _cartService.Get(account);

			// 預設帶入 訂房人資料
			cart.ContactProfile = _profileService.GetMemberProfile(account);
			return View(cart);
		}

		[Authorize]
		[HttpPost]
		public ActionResult OrderInfo(CartVm vm)
		{
			if (!ModelState.IsValid) return View(vm);

			// 檢查購物車要有項目 才能後續動作 todo: 給前端錯誤訊息
			if (!vm.Items.Any()) { return View(vm); }

			var account = User.Identity.Name;
			var cart = _cartService.GetOrCreateCart(account);
			cart.AllowCheckout = cart.Items.Any();

			if (cart.AllowCheckout == false)
			{
				ModelState.AddModelError("", "購物車是空的,無法進行結帳");
				return View(vm);
			}

			foreach (var item in cart.Items)
			{
				item.RoomName = vm.Items.FirstOrDefault(x => x.Id == item.Id).RoomName;
			}
			cart.ContactProfile = vm.ContactProfile;
			cart.Coupon = vm.Coupon;
			cart.PaymentType = vm.PaymentType;

			var orderId = _cartService.ProcessCheckout(account, cart);
			return RedirectToAction("Pay", "Orders", new { orderId = orderId }); // 轉導到 Orders/Pay 並帶入參數: orderId
		}

		/// <summary>
		/// 將 CartItem加入購物車
		/// </summary>
		/// <param name="vm"></param>
		/// <returns></returns>
		[Authorize]
		[HttpPost]
		public string AddItem(CartItemsVm vm)
		{
			string buyer = User.Identity.Name; // 買家帳號
			var result = _cartService.AddToCart(buyer, vm); //加入購物車

			return result; //沒傳回任何東西
		}

		//[Authorize]
		//public ActionResult Checkout()
		//{
		//	var buyer = User.Identity.Name;
		//	var cart = _cartService.GetOrCreateCart(buyer);

		//	if (cart.AllowCheckout == false) ViewBag.ErrorMessage = "購物車是空的,無法進行結帳";

		//	return View();
		//}

		//[Authorize]
		//[HttpPost]
		//public ActionResult Checkout(CheckoutVm vm)
		//{
		//	if (!ModelState.IsValid) return View(vm);

		//	var cartService = _cartService;

		//	var buyer = User.Identity.Name;
		//	var cart = cartService.GetOrCreateCart(buyer);

		//	if (cart.AllowCheckout == false)
		//	{
		//		ModelState.AddModelError("", "購物車是空的,無法進行結帳");
		//		return View(vm);
		//	}

		//	//cartService.ProcessCheckout(buyer, cart, vm);
		//	return View("ConfirmCheckout");
		//}

		public ActionResult DeleteCartItem(int cartItemId)
		{
			_cartService.DeleteCartItem(cartItemId);
			return new EmptyResult();
		}
	}
}

FProjectCamping/Views/Carts/Cart.cshtml
@model FProjectCamping.Models.ViewModels.Carts.CartVm

@{
    ViewBag.Title = "購物車";
}

@section css{
    <link rel="stylesheet" href="~/css/Progress.css">
    <link rel="stylesheet" href="~/css/Cart.css" />
}
@using (Html.BeginForm("Cart", "Carts", FormMethod.Post))
{
    <div class="main">
        <div class="container mt-5 mb-5">
            <div class="cartarea">

                <div class="cartPage">

                    <!--進度條 begin-->
                    <ul class="progressarea">
                        <li class="active">購物車</li>
                        <li>訂單資料</li>
                        <li>建立訂單</li>
                        <li>付款</li>
                    </ul>
                    <!--進度條 end-->
                    <!-- 表格部分 -->
                    <table class="tabledetail">
                        <thead>
                            <tr>
                                <th>營區房型</th>
                                <th>房號</th>
                                <th>入住日</th>
                                <th>退房日</th>
                                <th>單價</th>
                                <th>夜數</th>
                                <th>加床</th>
                                <th>加床金額</th>
                                <th>金額</th>
                                <th>移除</th>
                            </tr>
                        </thead>
                        <tbody id="tableBody">
                            @if (Model.Items != null)
                            {
                                for (var i = 0; i < Model.Items.Count; i++)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(model => model.Items[i].RoomName)</td>
                                        <td>@Html.DisplayFor(model => model.Items[i].RoomNum)</td>
                                        <td>@Html.DisplayFor(model => model.Items[i].CheckInDate)</td>
                                        <td>@Html.DisplayFor(model => model.Items[i].CheckOutDate)</td>
                                        <td>@Html.DisplayFor(model => model.Items[i].RoomPrice)</td>
                                        <td>@Html.DisplayFor(model => model.Items[i].Days)</td>
                                        <td>
                                            @Html.CheckBoxFor(model => model.Items[i].ExtraBed, new { onchange = "updateSubTotal(this, " + Model.Items[i].ExtraPrice + ")" })
                                        </td>
                                        <td data-extraPrice>@(Model.Items[i].ExtraBed ? Model.Items[i].ExtraBedPrice.ToString() : "0")</td>
                                        <td data-subtotal>@Html.DisplayFor(model => model.Items[i].SubTotal)</td>
                                        <td>
                                            <button class="delete-button" onclick="removeRow(this, @Model.Items[i].SubTotal)">刪除</button>
                                        </td>
                                        <td>
                                            @*統一將欄位傳回後端更新*@
                                            @Html.HiddenFor(model => model.Items[i].Id)
                                            @Html.HiddenFor(model => model.Items[i].RoomTypeId)
                                            @Html.HiddenFor(model => model.Items[i].RoomId)
                                            @Html.HiddenFor(model => model.Items[i].CheckInDate)
                                            @Html.HiddenFor(model => model.Items[i].CheckOutDate)
                                            @Html.HiddenFor(model => model.Items[i].RoomPrice)
                                            @Html.HiddenFor(model => model.Items[i].Days)
                                            @Html.HiddenFor(model => model.Items[i].ExtraBed)
                                            @Html.HiddenFor(model => model.Items[i].ExtraBedPrice)
                                            @Html.HiddenFor(model => model.Items[i].SubTotal)
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="11">無資料</td>
                                </tr>
                            }
                        </tbody>
                    </table>

                    <div class="totalArea">
                        <span>小計：</span><span id="total" name="TotalPrice">@Model.TotalPrice</span>
                    </div>
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.MemberAccount)
                    @Html.HiddenFor(model => model.TotalPrice)
                    <div class="bottomArea">
                        <button type="button" id="back">上一頁</button>
                        <button type="submit" id="next">下一頁</button>
                    </div>
                    <!-- 表格部分 -->
                </div>
            </div>
        </div>
    </div>
}
@section scripts{
    @if (Model.Items == null)
    {
        <script>
            Swal.fire({
                position: 'center',
                icon: 'warning',
                title: '請至少預定一間房才可下一步！'
            });
        </script>
    }
    <script>
 // 0925 rabbit
        document.getElementById('back')
            .addEventListener('click', function ()
            {
                window.location.href = '@Url.Action("Roomtype", "Rooms")';
        });
    </script>
    <script>
        //Swal.fire({
        //    position: 'top-end',
        //    icon: 'success',
        //    title: 'Your work has been saved',
        //    showConfirmButton: false,
        //    timer: 1500
        //})
        // 取得全部的 subtotal 元素
        var subTotalCells = document.querySelectorAll('[data-subtotal]');

        // 取得顯示總金額的元素
        var totalLabel = document.getElementById('total');

        // 定義 MutationObserver
        var mutationObserver = new MutationObserver(function (mutationsList) {
            updateTotal();
        });

        // 監聽每個 subtotal 元素的變化
        subTotalCells.forEach(function (subTotalCell) {
            mutationObserver.observe(subTotalCell, { childList: true });
        });

        // 初次執行一次，讓畫面初始化有正確的金額
        updateTotal();

        // 更新總金額的函數
        function updateTotal() {
            var total = 0;

            subTotalCells.forEach(function (subTotalCell) {
                total += parseInt(subTotalCell.textContent);
            });

            // 更新顯示總金額的元素
            totalLabel.textContent = total.toLocaleString();

            var hiddenTotalPrice = document.getElementById("TotalPrice");
            hiddenTotalPrice.value = total; // 更新值
        }

        // checkbox勾選 需更新 SubTotal
        function updateSubTotal(checkbox, price) {
            var row = checkbox.parentNode.parentNode;
            var subTotalCell = row.querySelector('[data-subtotal]'); // SubTotal 的位置
            var extraPriceCell = row.querySelector('[data-extraPrice]'); // ExtraPrice 的位置
            var subTotal = parseInt(subTotalCell.textContent); // 當前 SubTotal 的值

            var hiddenSubTotal = row.querySelector('[name*=".SubTotal"]');
            var hiddenExtraBedPrice = row.querySelector('[name*=".ExtraBedPrice"]');

            // 勾選 ExtraBed 加 SubTotal
            if (checkbox.checked) {
                subTotal += price;
                extraPriceCell.textContent = price;
                hiddenExtraBedPrice.value = price;
            } else { // 如果取消勾選 ExtraBed，将 ExtraPrice 從 SubTotal 扣除
                subTotal -= price;
                extraPriceCell.textContent = 0;
                hiddenExtraBedPrice.value = 0;
            }

            // 更新畫面上 SubTotal 的顯示值
            subTotalCell.textContent = subTotal;
            // 更新 hidden 的值
            hiddenSubTotal.value = subTotal;

        }

        // 移除
        function removeRow(button) {
            // 移除選定的元素
            // button的父元素的父元素
            var row = button.parentNode.parentNode;
            row.parentNode.removeChild(row);

            // 更新 subtotal 的值，假設你的 subtotal 元素有一個 data-subtotal 屬性
            var subTotalCell = row.querySelector('[data-subtotal]');
            var currentSubTotal = parseInt(subTotalCell.textContent, 10);
            subTotalCell.textContent = 0; // 將被刪除的行的 subtotal 設為 0

            // 更新 total 的值
            var total = document.getElementById("total");
            var currentTotal = parseInt(total.textContent, 10);
            var newTotal = currentTotal - currentSubTotal;

            // 更新總金額
            total.textContent = newTotal.toLocaleString();
        }
    </script>
}

FProjectCamping/Views/Carts/OrderInfo.cshtml
@model FProjectCamping.Models.ViewModels.Carts.CartVm

@{
    ViewBag.Title = "訂單資料";
}

@section css{
    <link rel="stylesheet" href="~/css/Progress.css">
    <link rel="stylesheet" href="~/css/OrderInfo.css">
}
@using (Html.BeginForm("OrderInfo", "Carts", FormMethod.Post, new { onsubmit = "return checkPaymentType();" }))
{
    <div class="conatiner">
        <div class="main">
            <div class="container mt-5 mb-5">
                <div class="orderInfoarea">

                    <div class="orderInfoPage">

                        <!--進度條 begin-->
                        <ul class="progressarea">
                            <li>購物車</li>
                            <li class="active">訂單資料
                            <li>建立訂單</li>
                            <li>付款</li>
                        </ul>
                        <!--進度條 end-->
                        <!-- 表格部分 -->
                        <table class="tabledetail">
                            <thead>
                                <tr>
                                    <th>營區房型</th>
                                    <th>房號</th>
                                    <th>入住日</th>
                                    <th>退房日</th>
                                    <th>單價</th>
                                    <th>夜數</th>
                                    <th>加床</th>
                                    <th>加床金額</th>
                                    <th>金額</th>
                                </tr>
                            </thead>
                            <tbody id="tableBody">
                                @for (var i = 0; i < Model.Items.Count; i++)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(model => model.Items[i].RoomName)</td>
                                        <td>@Html.DisplayFor(model => model.Items[i].RoomNum)</td>
                                        <td>@Html.DisplayFor(model => model.Items[i].CheckInDate)</td>
                                        <td>@Html.DisplayFor(model => model.Items[i].CheckOutDate)</td>
                                        <td>@Html.DisplayFor(model => model.Items[i].RoomPrice)</td>
                                        <td>@Html.DisplayFor(model => model.Items[i].Days)</td>
                                        <td>
                                            @Html.CheckBoxFor(model => model.Items[i].ExtraBed, new { disabled = "disabled" })
                                        </td>
                                        <td data-extraPrice>@(Model.Items[i].ExtraBed ? Model.Items[i].ExtraBedPrice.ToString() : "0")</td>
                                        <td data-subtotal>@Html.DisplayFor(model => model.Items[i].SubTotal)</td>
                                        @*統一將欄位傳回後端更新*@
                                        @Html.HiddenFor(model => model.Items[i].Id)
                                        @Html.HiddenFor(model => model.Items[i].RoomName)
                                    </tr>
                                }
                            </tbody>
                        </table>
                        @Html.HiddenFor(model => model.Id)

                        <!--優惠碼專區 begin-->
                        <div class="calPrice">
                            @*<div class="coupon">
                                    <label for="coupon">優惠碼：</label>
                                    <input type="text" id="coupon" name="coupon">
                                    @Html.HiddenFor(model => model.Coupon)
                                    <button type="button" id="applyCouponButton">使用</button>
                                </div>*@
                            <div class="total">
                                @*<span>小計：</span><span id="total">@Model.TotalPrice</span>
                                    <br>*@
                                @*<span>折扣：</span><span id="discount"></span>*@
                                <br>
                                <span>總金額：</span><span id="total" name="TotalPrice">@Model.TotalPrice</span>
                                @Html.HiddenFor(model => model.TotalPrice)
                            </div>
                        </div>
                        <!--優惠碼專區 end-->

                        <div class="bottomArea">
                            <button type="button" id="back">上一頁</button>
                            <button type="submit" id="next">下一步</button>
                        </div>
                        <div class="buyerInfo">

                            <div class="buyerInfo-data">

                                <label for="buyerInfo-title">訂房人資料</label><br><br>

                                <label for="name"><span>*</span>姓名：</label>
                                <input type="text" id="name" name="name" required value="@Model.ContactProfile.Name"><br><br>
                                @Html.HiddenFor(model => model.ContactProfile.Name)

                                <label for="phone"><span>*</span>電話號碼：</label>
                                <input type="tel" id="phone" name="phone" required value="@Model.ContactProfile.PhoneNum"><br><br>
                                @Html.HiddenFor(model => model.ContactProfile.PhoneNum)

                                <label for="email"><span>*</span>電子郵件：</label>
                                <input type="email" id="email" name="email" required value="@Model.ContactProfile.Email"><br><br>
                                @Html.HiddenFor(model => model.ContactProfile.Email)

                                <label for="PaymentType"><span>*</span>付款方式：</label>
                                <select id="PaymentType" name="PaymentType">
                                    <!-- 預設選項 -->
                                    <option value="" disabled selected>請選擇付款方式</option>
                                    <!-- 預先設定的付款方式選項 -->
                                    <option value=1>現金</option>
                                    <option value=2>PayPal</option>
                                    <option value=3>銀行轉帳</option>
                                </select>
                                @Html.HiddenFor(model => model.PaymentType)
                            </div>

                            <div class="buyerInfo-memo">
                                <label for="memo">備註：</label>
                                <textarea name="memo" rows="4" cols="50" placeholder="如您有特殊需求，可以在此欄位註明。"></textarea>
                                @Html.HiddenFor(model => model.Memo)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@section scripts{
    <script>
        $('#name').on('input', function () {
            $('input[name="ContactProfile.Name"]').val($(this).val());
        });

        $('#phone').on('input', function () {
            $('input[name="ContactProfile.PhoneNum"]').val($(this).val());
        });

        $('#email').on('input', function () {
            $('input[name="ContactProfile.Email"]').val($(this).val());
        });

        // 0925 rabbit
        document.getElementById('back')
            .addEventListener('click', function ()
            {
                window.location.href = '@Url.Action("Cart", "Carts")';
            });

        function checkPaymentType() {
            var paymentType = document.getElementById("PaymentType").value;
            if (paymentType === "") {
                alert("請選擇付款方式！");
                return false;
            }
            return true;
        }
    </script>
}